package:
  name: eukfinder
  version: "1.2.3"

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('eukfinder', max_pin="x") }}

source:
  url: https://github.com/RogerLab/Eukfinder/archive/refs/tags/v1.2.3.tar.gz
  sha256: 8b8235049084e8c7171ce8968b07be25bad9b9979ce1f04cfe4b8690f5641a7d

requirements:
  build:
    - wget
    - python >=3.6,<3.7
    - setuptools
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - python >=3.6,<3.7
    - setuptools
  run:
    - python >=3.6,<3.7
    - ete3
    - numpy
    - pandas
    - joblib
    - pyqt =5
    - spades
    - seqkit
    - trimmomatic
    - centrifuge
    - bowtie2


test:
  commands:
    - df -h
    - plast -h
    - acc2tax --help
    - eukfinder --help
    - eukfinder read_prep -h
    - eukfinder short_seqs -h
    - eukfinder long_seqs -h
    - df -h

about:
  home: https://github.com/RogerLab/Eukfinder
  license: MIT
  license_file: LICENCE.txt
  summary: "Eukfinder is a tool for detecting eukaryotic sequences in metagenomic data."
