package:
  name: eukfinder
  version: "1.2.3"

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('eukfinder', max_pin="x") }}

source:
  url: https://github.com/RogerLab/Eukfinder/archive/refs/tags/v1.2.3.tar.gz
  sha256: c576243ded5c5952b42ce19c5a09b1a9a95d9f2b745d7033f390f4011a02c6ea

requirements:
  build:
    - wget
    - python
    - setuptools
    - pip
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  run:
    - python

test:
  commands:
    - source $(conda info --base)/etc/profile.d/conda.sh
    - conda activate eukfinder
    - eukfinder --help

about:
  home: https://github.com/RogerLab/Eukfinder
  license: MIT
  license_file: LICENCE.txt
  summary: "Eukfinder is a tool for detecting eukaryotic sequences in metagenomic data."
