package:
  name: eukfinder
  version: "1.2.3"

source:
  git_url: https://github.com/RogerLab/Eukfinder.git
  git_rev: HEAD
  git_depth: 1
  sha256: unused

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:

about:
  home: https://github.com/RogerLab/Eukfinder
  license: MIT
  license_file: LICENCE.txt
  summary: "A bioinformatics tool designed to enable rapid recovery of high-quality draft genomes of microbial 
  eukaryotes from various environmental metagenomic samples."
