package:
  name: eukfinder
  version: "1.2.3"

build:
  number: 0
  script: $PYTHON setup.py install --single-version-externally-managed --record=record.txt
  run_exports:
    - {{ pin_subpackage('eukfinder', max_pin="x") }}

source:
  url: https://github.com/RogerLab/Eukfinder/archive/refs/tags/v1.2.3.tar.gz
  sha256: 61076c15ff3906c2ed8d4c7ad30c9d256748fe77af800f85bb843225bcc9d100

requirements:
  build:
    - wget
    - python
    - setuptools
    - pip
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  run:
    - python

test:
  commands:
    - source $(conda info --base)/etc/profile.d/conda.sh
    - conda activate eukfinder
    - eukfinder --help

about:
  home: https://github.com/RogerLab/Eukfinder
  license: MIT
  license_file: LICENCE.txt
  summary: "Eukfinder is a tool for detecting eukaryotic sequences in metagenomic data."
