package:
  name: eukfinder
  version: "1.2.3"

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('eukfinder', max_pin="x") }}

source:
  url: https://github.com/RogerLab/Eukfinder/archive/refs/tags/v1.2.3.tar.gz
#  this is garbage
  sha256: 52b496835bf51b5a42d2fda4f1a1f9d10bf082220f62fe66169a3e346cd1f298

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:

test:
  commands:
    - eukfinder --help

about:
  home: https://github.com/RogerLab/Eukfinder
  license: MIT
  license_file: LICENCE.txt
  summary: "Eukfinder is a tool for detecting eukaryotic sequences in metagenomic data."
