package:
  name: eukfinder
  version: "1.2.3"

source:
  git_url: https://github.com/RogerLab/Eukfinder.git
  git_rev: HEAD
  git_depth: 1
  sha256: unused

requirements:
  build:
    - python
    - wget
    - tar
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

test:
  commands:
    - conda activate eukfinder
    # Verify PLAST installation
    - export PATH=$PWD/plastbinary_linux_v2.3.2/build/bin:$PATH
    - plast -h || { echo 'PLAST installation failed'; exit 1; }
    # Verify acc2tax build
    - ./acc2tax --help || { echo 'acc2tax build failed'; exit 1; }
    # Verify eukfinder sub-calls
    - cd ../bin/
    - python Eukfinder.py read_prep -h
    - python Eukfinder.py short_seqs -h
    - python Eukfinder.py long_seqs -h

about:
  home: https://github.com/RogerLab/Eukfinder
  license: MIT
  license_file: LICENSE
  summary: "A bioinformatics tool designed to enable rapid recovery of high-quality draft genomes of microbial 
  eukaryotes from various environmental metagenomic samples."
